config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root to: 'visitors#index'
  
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :phone, :string
  attr_accessor :message, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :phone
  validates_presence_of :message
  validates_format_of :email,
    with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :message, :maximum => 500

end

app/models/visitor.rb
class Visitor
  include ActiveModel::Model
  attr_accessor :email, :string
  validates_presence_of :email
  validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    list_id = Rails.application.secrets.mailchimp_list_id
    result = mailchimp.lists(list_id).members.create(
      body: {
        email_address: self.email,
        status: 'subscribed'
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      UserMailer.contact_email(@contact).deliver_now
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :phone, :message)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/contacts/new.html.erb
<!-- Page Header -->
<% content_for :title do %>Contact<% end %>
<header class="intro-header" style="background-color: black">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>Contact Me</h1>
            <hr class="small">
              <span class="subheading">Have questions? I have answers (maybe).</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
      <%= form_for @contact do |form| %>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= form.text_field :name, placeholder: 'Name', :class => 'form-control' %>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= form.text_field :email, placeholder: 'Email Address', :class => 'form-control' %>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= form.text_field :phone, placeholder: 'Phone Number', :class => 'form-control' %>
          </div>
        </div>
        <div class="row control-group">
          <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= form.text_area :message, placeholder: 'Message', :class => 'form-control' %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="form-group col-xs-12">
            <%= form.submit "Send", :class => "btn btn-default" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr>

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Coder-Blog 2016</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Coder-Blog', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
        <!-- /.navbar-collapse -->
  </div>
    <!-- /.container -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
    <%= link_to 'Home', root_path %>
</li>
<li>
    <%= link_to 'About', page_path('about') %>
</li>
<li>
    <%= link_to 'Post', page_path('post') %>
</li>
<li>
    <%= link_to 'Contact', new_contact_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Coder-Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Coder-Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div>
      <header>
        <%= render 'layouts/navigation' %>
      </header>

      <%= render 'layouts/messages' %>
    
      <%= yield %>
    
      <%= render 'layouts/footer' %>
    
      <script id="dsq-count-scr" src="//coderblog4.disqus.com/count.js" async></script>
    
    </div>
  
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<!-- Page Header -->
<header class="intro-header" style="background-color: black">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>About Me</h1>
            <hr class="small">
              <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
    </div>
  </div>
</div>

app/views/pages/post.html.erb
<% content_for :title do %>Post<% end %>
<!-- Page Header -->
<header class="intro-header" style="background-color: black">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>Man must explore, and this is exploration at its greatest</h1>
            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
              <span class="meta">Posted by <a href="#">Aasish Sharma</a> on September 24, 2015</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

        <h2 class="section-heading">The Final Frontier</h2>

        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

        <blockquote>The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

        <h2 class="section-heading">Reaching for the Stars</h2>

        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

        <a href="#">
          <img class="img-responsive" src="http://i.imgur.com/KFU6qGn.jpg?1" alt="">
        </a>
        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
      </div>
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div id="disqus_thread"></div>
    <script>
    /*
    var disqus_config = function () {
      this.page.url = PAGE_URL; 
      this.page.identifier = PAGE_IDENTIFIER;
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');

      s.src = '//coderblog4.disqus.com/embed.js';

      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
    })();

    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
  </div>
    </div>
  </div>
</article>

app/views/visitors/index.html.erb
<!-- Page Header -->
<header class="intro-header" style="background-color: black">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Coder-Blog</h1>
            <hr class="small">
              <span class="subheading">A Blogging Web App by Aasish Sharma</span>
        </div>
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <%= form_for Visitor.new do |form| %>
            <div class="row">
              <div class="form-group col-xs-12">
                <%= form.text_field :email, label: false, :placeholder => 'Your email address', :class => "form-control" %>
              </div>
            </div>
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <div class="row">
                <div class="form-group col-xs-12">
                  <%= form.submit "Sign up for the newsletter", :class => "submit btn btn-default" %>
                </div>
              </div>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="post-preview">
        <%= link_to page_path('post') do %>
          <h2 class="post-title">
            Man must explore, and this is exploration at its greatest
          </h2>
          <h3 class="post-subtitle">
            Problems look mighty small from 150 miles up
          </h3>
        <% end %>
        <p class="post-meta">Posted by <a href="#">Aasish Sharma</a> on September 24, 2015</p>
      </div>
      <hr>
      <div class="post-preview">
        <%= link_to page_path('post') do %>
          <h2 class="post-title">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet.
          </h2>
        <% end %>
        <p class="post-meta">Posted by <a href="#">Aasish Sharma</a> on September 18, 2015</p>
      </div>
      <hr>
      <div class="post-preview">
        <%= link_to page_path('post') do %>
          <h2 class="post-title">
            Numquam at quae voluptatum in officia
          </h2>
          <h3 class="post-subtitle">
            Eius praesentium recusandae illo eaque architecto error, repellendus iusto.
          </h3>
        <% end %>
        <p class="post-meta">Posted by <a href="#">Aasish Sharma</a> on August 24, 2015</p>
      </div>
      <hr>
      <div class="post-preview">
        <%= link_to page_path('post') do %>
          <h2 class="post-title">
            Nostrum molestiae debitis
          </h2>
          <h3 class="post-subtitle">
            placeat magni repudiandae accusantium fugit quas labore non rerum possimus.
          </h3>
        <% end %>
        <p class="post-meta">Posted by <a href="#">Aasish Sharma</a> on July 8, 2015</p>
      </div>
      <hr>
      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="#">Older Posts &rarr;</a>
        </li>
      </ul>
    </div>
  </div>
</div>